apiVersion: v2
name: taqa-doa
description: A Helm chart for TAQA DOA application (server, client, editor)
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - taqa
  - doa
  - document
maintainers:
  - name: TAQA Team
    email: team@taqa.local
